public enum EventDefine
{
    AddDiamond,
    AddScore,
    DecidePath,
    IsMusicOn,
    PlayerMove,
    PlayButtonAudioClip,
    ShowHint,
    ShowGamePanle,
    ShowGameOverPanel,
    ShowMainPanel,
    ShowRankPanel,
    ShowResetPanel,
    ShowShopPanel,
    UpdateDiamonText,
    UpdateScoreText,
    ChangeSkin,
}
